all: run_hw2.py 
	python run_hw2.py --env_name CartPole-v0 -n 300 -b 4000 --exp_name cartpole_lb

t1: run_hw2.py
	python run_hw2.py --env_name CartPole-v0 -n 100 -b 1000 --exp_name cartpole

t2: run_hw2.py
	python run_hw2.py --env_name CartPole-v0 -n 100 -b 1000 --exp_name cartpole_rtg -rtg

t3: run_hw2.py
	python run_hw2.py --env_name CartPole-v0 -n 100 -b 1000 --exp_name cartpole_na -na

t4: run_hw2.py
	python run_hw2.py --env_name CartPole-v0 -n 100 -b 1000 --exp_name cartpole_rtg_na -rtg -na

t5: run_hw2.py
	python run_hw2.py --env_name CartPole-v0 -n 100 -b 4000 --exp_name cartpole_lb

t6: run_hw2.py
	python run_hw2.py --env_name CartPole-v0 -n 100 -b 4000 --exp_name cartpole_lb_rtg -rtg

t7: run_hw2.py
	python run_hw2.py --env_name CartPole-v0 -n 100 -b 4000 --exp_name cartpole_lb_na -na

t8: run_hw2.py
	python run_hw2.py --env_name CartPole-v0 -n 100 -b 4000 --exp_name cartpole_lb_rtg_na -rtg -na